set(sources ${sources}
    src/plugin.cpp
    src/Aim.cpp
    src/Captures.cpp
    src/Editor.cpp
    src/Eraser.cpp
    src/Markers.cpp
    src/Overrides.cpp
    src/Palette.cpp
    src/Palette.Placed.cpp
    src/Catalog.cpp
    src/CatalogFile.cpp
    src/Numpad.cpp
    src/Preview.cpp
    src/Physics.cpp
    src/Referrer.cpp
    src/Requires.cpp
    src/SceneExporter.cpp
    src/SceneExporter.Placements.cpp
    src/SceneExporter.Registries.cpp
    src/SceneExporter.Captures.cpp
    src/UI.cpp
    src/UI.Browser.cpp
    src/UI.Fields.cpp
    src/UI.Markers.cpp
    src/UI.References.cpp
    src/UI.Settings.cpp
    src/Modes.cpp
    src/KeyIni.cpp
    src/Console.cpp
    src/CoSave.cpp
    src/CoSave.Settings.cpp
    src/CoSave.Registries.cpp
    src/CoSave.Captures.cpp
)
